### ISSUE TITLE
Unknown instrument:​ Screenshot (at Connection.js:​162:​29)​

### ISSUE THREAD

**Issue by Heath123** [HimbeersaftLP/ios-safari-remote-debug-kit#12]
![image](https://user-images.githubusercontent.com/13787163/197296518-2aed6d6b-81b9-4673-86c4-cab895fcd562.png)
Happens with both Chromium and Gnome Web

**Comment by ssz66666** [comment]
Referring to this: https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/blob/main/HOW_IT_WORKS.md#selecting-the-version

Make sure the version of `InspectorBackendCommands.js` used either **matches** or **is lower than** your iOS version. The scripts `generate.sh` / `generate.ps1` always use the latest version available in the WebKit repository but that might not be what your iOS device supports.

Perhaps it would be more user-friendly to list all versions found in `WebKit/Source/WebInspectorUI/UserInterface/Protocol/Legacy/iOS`, and prompt to let the user choose which version to use.

**Comment by HimbeersaftLP** [comment]
Hi, I added that feature in this PR (PowerShell only so far): https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/pull/14

Can you test if selecting iOS 15.4 works for you @Heath123?

**Comment by HimbeersaftLP** [comment]
Bash variant is also available now

**Comment by HimbeersaftLP** [comment]
@Heath123 Can I close this issue?

**Comment by Heath123** [comment]
Sorry, I don’t need this any more or really remember what I did, so I can’t test it now (though if you really want me to I could get it set up again)

Thanks for the fix anyway though

**Comment by HimbeersaftLP** [comment]
Nah I'm fine, it works fine on the latest iOS and I tested if the argument would place the correct file so I can't imagine it not working. Thanks for the offer though!
