### ISSUE TITLE
Unable to attach inspector / iOS 16 issues?

### ISSUE THREAD

**Issue by Gandalf1783** [HimbeersaftLP/ios-safari-remote-debug-kit#13]
I get this in the 2nd CMD Window thats opening:
```
Listing devices on :9221
Could not start com.apple.webinspector!: No error
Unable to attach 00008120-001E250C110B401E inspector

```
While the powershell window instructs me to open the localhost:8080 stuff, it does not show errors:
```
====================================================================================
Will try to launch a web server on http://localhost:8080
You can then open http://localhost:8080/Main.html?ws=localhost:9222/devtools/page/1
in a Chromium or WebKit based browser to start debugging.
Press Ctrl+C to exit.
====================================================================================

Searching web server
Found Python 3, using it to serve the WebInspector
```

Using an iPhone 14, with iOS 16.0.3 on it. 
Could not get any debuggin software to start yet.

**Comment by HimbeersaftLP** [comment]
Appears to be related to #4 and #7.

Make sure iTunes is installed and your PC is "trusted" by your iOS device. (Check if you can transfer music with iTunes)

**Comment by Gandalf1783** [comment]
Itunes is installed and up-to-date.

I didnt sync any music yet, but I have access to all the files through the app manager. I can only assume it is trusted because I did not get any popup for trusting.

**Comment by HimbeersaftLP** [comment]
Hmm, did you also double-check if the Web Inspector is enabled in Safari settings and you are using Safari and not another browser?

**Comment by Gandalf1783** [comment]
Pretty sure, I was able to debug in Safari using another non-free Software just fine.

**Comment by HimbeersaftLP** [comment]
Can you try adding `--debug` to the argument list here:
https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/blob/9e86469f1a140f4ea88762f1888875fa5d515de6/src/start.ps1#L72

```ps1
$debugProxyProc = Start-Process $debugProxyExe -ArgumentList "--no-frontend --debug" -PassThru
```

**Comment by Gandalf1783** [comment]
Sure, I will try when I'm home again.

**Comment by cativo** [comment]
could it  be related to this : https://github.com/google/ios-webkit-debug-proxy/issues/61#issuecomment-200089042?

**Comment by Gandalf1783** [comment]
I finally had time to try this out.

The Log insinde the extra window that pops up is this:
```
ss.add_server_fd(444)
Listing devices on :9221
ss.add_fd(448)
ss.add_server_fd(644)
ss.remove_server_fd(644)
ss.recv fd=448 len=960
ss.add_server_fd(664)
Could not start com.apple.webinspector!: No error
ss.remove_server_fd(664)
Unable to attach 00008120-001E250C110B401E inspector
ss.accept server=444 new_client=696
ss.add_fd(696)
```

**Comment by varndellwagglebee** [comment]
I'm having the same issue.  Here is what I get with the debug
```
ss.add_server_fd(452)
Listing devices on :9221
ss.add_fd(460)
ss.add_server_fd(656)
ss.remove_server_fd(656)
ss.recv fd=460 len=958
ss.add_server_fd(660)
Could not start com.apple.webinspector!: No error
ss.remove_server_fd(660)
Unable to attach 00008110-000E35020A31801E inspector
```

**Comment by HimbeersaftLP** [comment]
@Gandalf1783 @cativo @varndellwagglebee It looks like this is a known issue of ios-webkit-debug-proxy as it is listed in their README: https://github.com/google/ios-webkit-debug-proxy#could-not-start-comapplewebinspector-success
Though it looks like they only have advice for Linux.

**Comment by Gandalf1783** [comment]
Is it known which part exactly fails?
If it is just a USB-Lib Call from Windows, maybe we have to adjust the parameters. 

I was able to get a debug-session up using some proprietary/paid software, which worked just fine.

I therefore assume that its possible to fix this.

**Comment by HimbeersaftLP** [comment]
@Gandalf1783 The error comes from this call to the libimobiledevice library: https://github.com/google/ios-webkit-debug-proxy/blob/12d5cd12e8d1803f7e5b64d8c4637db698de3d6a/src/webinspector.c#L157

Personally, I can't really debug the issue since I don't run into it.

**Comment by FanningHau** [comment]
Same issue here on Windows10 ,the test device is iPhone 14 Pro ,OS version is 16.2

**Comment by artygus** [comment]
did you try clearing up lockdown directory? `C:\ProgramData\Apple\Lockdown`? also make sure you have latest iTunes installed, version `12.12.7.1` atm

**Comment by laurenceks** [comment]
Also experiencing this issue - any news on whether this can/will be fixed or of a workaround?

**Comment by 17** [comment]
Windows11 ,the test device is iPhone 13 Ios16.4 , I don't run into it.

**Comment by c-eugenio** [comment]
Hey guys, i fixed it.

just update the link of the start.ps1 script to the latest ios-webkit-debug-proxy release.

line 19: 
```
$debugProxyUrl = "https://github.com/google/ios-webkit-debug-proxy/releases/download/v1.9.0/ios-webkit-debug-proxy-1.9.0-win64-bin.zip"
```

**Comment by laurenceks** [comment]
> Hey guys, i fixed it.
> 
> 
> 
> just update the link of the start.ps1 script to the latest ios-webkit-debug-proxy release.
> 
> 
> 
> line 19: 
> 
> ```
> 
> $debugProxyUrl = "https://github.com/google/ios-webkit-debug-proxy/releases/download/v1.9.0/ios-webkit-debug-proxy-1.9.0-win64-bin.zip"
> 
> ```
> 
> 
> 
> PS: make sure to delete the folder ios-webkit-debug-proxy before re-running start.ps1

This worked for me, thanks!

**Comment by Gandalf1783** [comment]
This was top easy :)

Thanks, will try out later!

**Comment by HimbeersaftLP** [comment]
I just pushed a new commit that will automatically update the version of ios-webkit-debug-proxy
https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/commit/0e7321f0530ced2cba22726a31e1eeed4375b84f

**Comment by HimbeersaftLP** [comment]
@Gandalf1783 @cativo @varndellwagglebee @FanningHau @HermanCodesAtWork @laurenceks @17 @arnoclr @superlucker Can you check if this works for you?

**Comment by Gandalf1783** [comment]
Now checking...

**Comment by Gandalf1783** [comment]
Since I moved from Windows to Linux in the meantime, I cant reliably check the current state of it working/not working.
I tried passing the device into a windows 10 vm.

My iPhone is recognized and the driver was installed by windows update.
However, in my case after running start.sh (even as admin) it exits out after "Running ios-webkit-debug-proxy".
This could be an issue with qemu, but currently I dont have any Windows-System near me to test it on direct hardware.
![image](https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/assets/46635221/88dbfd10-6259-4f3f-be08-40f7817c18a9)

**Comment by HimbeersaftLP** [comment]
@Gandalf1783 Thanks for taking the extra effort! Does the VM have iTunes installed?

**Comment by Gandalf1783** [comment]
No, completely missed that point 🙃
Will try after school with iTunes installed :)

**Comment by Gandalf1783** [comment]
Nope, a reboot did not fix it. The edge://inspect site lists a tab I actually opened on safari on my phone, but its not the current one and I also cannot click on "start debugging" -> nothing happens.

No errors in the powershell/cmd consoles:

![image](https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/assets/46635221/94304169-72ff-45ff-a977-d83a298fb24e)

**Comment by laurenceks** [comment]
> Nope, a reboot did not fix it. The edge://inspect site lists a tab I actually opened on safari on my phone, but its not the current one and I also cannot click on "start debugging" -> nothing happens.
> 
> 
> 
> No errors in the powershell/cmd consoles:
> 
> 
> 
> ![image](https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/assets/46635221/94304169-72ff-45ff-a977-d83a298fb24e)
> 
> 

If it helps I deleted the generated folders and re-ran generate, I also disabled python and used node

**Comment by HimbeersaftLP** [comment]
@Gandalf1783 Thanks for testing again!
As Lauren said, I think you're now running into the other known issue, which is the Python detection failing due to the Microsoft Store shortcut (#16)

**Comment by c-eugenio** [comment]
If it helps, I did not use Python for the server.

**Comment by HimbeersaftLP** [comment]
I fixed the Python issue in commit https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/commit/77620eb0e1bbbb12590a071bcc4bf9ce02916e27 btw

**Comment by HimbeersaftLP** [comment]
I'm going to assume this is fixed now. Thanks for reporting, feel free to reopen if anyone still experiences this issue.
