### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by metalllus** [HimbeersaftLP/ios-safari-remote-debug-kit#15]
Hi. I ran start.ps1. In one terminal window I have this:

Listing devices on :9221
Connected :9222 to iPhone (4) (00008030-00164D3A023B402E)

In the other I have this:
Entering script directory C:\Programming\ios_safari-remote-debug-kit\ios-safari-remote-debug-kit\src
Running ios-webkit-debug-proxy...
Entering C:\Programming\ios_safari-remote-debug-kit\ios-safari-remote-debug-kit\src

====================================================================================
Will try to launch a web server on http://localhost:8080
You can then open http://localhost:8080/Main.html?ws=localhost:9222/devtools/page/1
in a Chromium or WebKit based browser to start debugging.
Press Ctrl+C to exit.
====================================================================================

Searching web server
Found Python 3, using it to serve the WebInspector

When I open http://localhost:9222/ I can see this:

Inspectable pages for iPhone (4):
1. https://something.com/
2. ?
3. ?
4. https://something-else.com/

However if I open http://localhost:8080/Main.html?ws=localhost:9222/devtools/page/1 I get an error message:
This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED

I tried two different iPhones. One with iOS 15 and one with iOS 16. Same result.
Any ideas what the problem is?

**Comment by HimbeersaftLP** [comment]
Can you try opening the debugger on the debugger and check for the websocket connection in the "Network" tab?

**Comment by metalllus** [comment]
@HimbeersaftLP Could you please give more detailed instructions? I don't know what you mean. On the Network tab I get this:
![chrome_MiYikVBcPH](https://user-images.githubusercontent.com/48943750/220180773-c2a7babd-c4b9-40e3-a048-1183964c074d.png)

If I navigate just to http://localhost:8080/ I get the same thing.

**Comment by HimbeersaftLP** [comment]
oh, I think I know what the issue is. It's related to #2 
Try commenting out the python part of the powershell script and using nodejs with http-server instead

**Comment by metalllus** [comment]
@HimbeersaftLP, could you please explain how do i use nodejs with http-server instead? Am I supposed to replace the commented out line with something else using the nodejs http-server? I have it installed globally using npm but I do not know how to use it in this case.

**Comment by HimbeersaftLP** [comment]
You're welcome!
I'd love to bundle a simple webserver with the app, but all the minimal single-exectuable webservers get falsely detected by antivirus software because they're uncommon and usually packed.

**Comment by metalllus** [comment]
@HimbeersaftLP I understand, thanks for the effort anyway.

**Comment by HimbeersaftLP** [comment]
Added a workaround for this in commit 77620eb0e1bbbb12590a071bcc4bf9ce02916e27

**Comment by HimbeersaftLP** [comment]
@metalllus @scofield-ua @alsatian Added a workaround for this in commit https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/commit/77620eb0e1bbbb12590a071bcc4bf9ce02916e27
