### ISSUE TITLE
start.sh: line 11: $1: unbound variable

### ISSUE THREAD

**Issue by dnyall** [HimbeersaftLP/ios-safari-remote-debug-kit#17]
Distributor ID:	Ubuntu x86_64
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

when i run "start.ps1" after install all requirment.
i got : 
"Entering script directory /home/userName/ios-safari-remote-debug-kit/src
start.sh: line 11: $1: unbound variable

**Comment by HimbeersaftLP** [comment]
Oops, I messed up, by adding the set -u without changing that part. Just write anything as the first argument to the script.
./src/start.sh banana

**Comment by HimbeersaftLP** [comment]
Fixed by #20, thanks for reporting, thanks @lf- for fixing
