### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by dschor-cubicsearch** [HimbeersaftLP/ios-safari-remote-debug-kit#18]
Forgive me if I should know this, but is there a way to check memory usage with this?  I'm trying to find out why my safari is crashing and I see a lot of other cool stuff, but not active memory.

**Comment by HimbeersaftLP** [comment]
Hi @dschor-cubicsearch, sorry for the really late response, I completely missed this issue.

You can enable the memory row in the timeline tab of the debugger:
<img width="561" alt="chrome_2024-06-01_23-47-11" src="https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/assets/16354747/c6f6ce1b-c07d-408e-af1f-e3944ad91ca5">

You can find more info here: https://webkit.org/blog/6425/memory-debugging-with-web-inspector/

**Comment by HimbeersaftLP** [comment]
Please let me know if that is what you were looking for.

**Comment by HimbeersaftLP** [comment]
Closing this due to lack of response. Feel free to reopen if you still have an issue.
