### ISSUE TITLE
No webpage content but only the debug console

### ISSUE THREAD

**Issue by machsix** [HimbeersaftLP/ios-safari-remote-debug-kit#23]
Is this an expected behavior? I couldn't see the content of the webpage. Thanks for the great work

![image](https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/assets/28209092/69ceb757-54c3-4f75-99f2-7e43879c0fe4)

**Comment by HimbeersaftLP** [comment]
Yes, that is expected, mirroring of the screen is currently not supported.

**Comment by HimbeersaftLP** [comment]
Or do you mean the Elements tab did not show the elements of the website you are trying to debug?

**Comment by machsix** [comment]
The elements work fine. I mean the mirroring of the screen

**Comment by HimbeersaftLP** [comment]
I see, it should be possible theoretically, because it used to work in the Chrome debugger, but I haven't yet had the time to figure out how it works and implement it here.
