### ISSUE TITLE
Device shows up, but can't fix `InspectorFrontendHostStub.js:68 WebSocket connection to 'ws://localhost:9222/devtools/page/1' failed`

### ISSUE THREAD

**Issue by Helveg** [HimbeersaftLP/ios-safari-remote-debug-kit#24]
Hi!

Thanks for this probably very fidgety OS project. I can see my connected device, but I can't debug anything. What information should I provide to debug this?

I see my iPad listed on `:9221` under `:9222`, but following the URL the page stays blank, and when running `./start.ps1` none of the tabs contain any information and the titular error is hit.

**Comment by HimbeersaftLP** [comment]
Did you try replugging the device while your page to debug is open?

**Comment by Helveg** [comment]
Yes, it seems now though, after a reboot of both devices that everything is fine :)

**Comment by HimbeersaftLP** [comment]
Good to hear, thanks for letting me know. It's a bit finicky sometimes.
