### ISSUE TITLE
Script failure on path with space

### ISSUE THREAD

**Issue by MadMass** [HimbeersaftLP/ios-safari-remote-debug-kit#27]
Hi,
Please edit the script generate.sh on line 56 to cd "$SCRIPT_DIR"
Otherwise it fails to execute if the script path has a space in it.
I'm creating an issue as this is a small change so I would like to avoid the hassle of a pull request.
Regards

**Comment by MadMass** [comment]
start.sh:9 as well

**Comment by HimbeersaftLP** [comment]
Thanks, I have no idea how I missed that. Fixed by e70ed71bdc101007e9c490d759a4d20c1838ce65
