### ISSUE TITLE
WebKit Inspector missing files

### ISSUE THREAD

**Issue by michaelandre0** [HimbeersaftLP/ios-safari-remote-debug-kit#3]
Hi,

I followed the process on win11 and I get everything to work except that when I visit the page http://localhost:8080/Main.html?ws=localhost:9222/devtools/page/1, I have some errors.

https://imgur.com/a/yHWOEYu

`GET http://localhost:8080/WebKitAdditions/WebInspectorUI/WebInspectorUIAdditions.css net::ERR_ABORTED 404 (Not Found)
Main.html:978          
GET http://localhost:8080/WebKitAdditions/WebInspectorUI/WebInspectorUIAdditions.js net::ERR_ABORTED 404 (Not Found)
FileUtilities.js:54 Uncaught TypeError: InspectorFrontendHost.canSave is not a function
    at Function.canSave (FileUtilities.js:54:38)
    at Object.WI._updateDownloadTabBarButton (Main.js:2560:27)
    at HTMLDocument.WI.contentLoaded (Main.js:466:8)
canSave @ FileUtilities.js:54
WI._updateDownloadTabBarButton @ Main.js:2560
WI.contentLoaded @ Main.js:466
favicon.ico:1          
GET http://localhost:8080/favicon.ico 404 (Not Found)
InspectorFrontendHostStub.js:68 WebSocket connection to 'ws://localhost:9222/devtools/page/1' failed: `

It turns out there is a missing folder in \ios-safari-remote-debug-kit\src\WebKit\Source\WebInspectorUI\UserInterface.

It seems to be missing the WebKitAdditions folder and from there, I don't know what I can do...

Any idea ?

Thank you !

**Comment by Zeiffelin** [comment]
Any news on this? I'm facing the same issue.

**Comment by HimbeersaftLP** [comment]
Sorry I was very busy lately. Fixed in 9633a14535bd99adf0fdf052679bdd72ab5350d6

The 404 was not the problem, that is some internal style used on Safari on the Mac. The problem were the missing functions (second error) in the InspectorFrontendHost.

Update your local copy of this repo, delete the `WebKit` folder, then run the generate script again, then it should be fixed.
