### ISSUE TITLE
Missing WebInspectorUIAdditions.js (and css) file

### ISSUE THREAD

**Issue by MaZZly** [HimbeersaftLP/ios-safari-remote-debug-kit#32]
When I load `http://localhost:8080/Main.html...` in the browser, I see that these files fail to load (404)
- `http://localhost:8080/WebKitAdditions/WebInspectorUI/WebInspectorUIAdditions.css`
- `http://localhost:8080/WebKitAdditions/WebInspectorUI/WebInspectorUIAdditions.js`

When moving the cursor on the debug page it triggers the following error (anytime cursor is moved):
```
Uncaught ReferenceError: Float16Array is not defined
```
(I'm guessing `Float16Array` would be defined in the missing JS file)

There are also these errors a bit earlier in the log:
```
Error saving setting with name: debugger-statements-breakpoint save @ Setting.js:126
Error saving setting with name: all-exceptions-breakpoint save @ Setting.js:126
Error saving setting with name: uncaught-exceptions-breakpoint save @ Setting.js:126
```

Wondering why those files would be missing, and where they can be found? :thinking:

**Comment by HimbeersaftLP** [comment]
Those files have always been missing. Given their name I assume they are proprietary additions specific to Safari.

**Comment by HimbeersaftLP** [comment]
Float16Array is an upcoming data type: https://caniuse.com/mdn-javascript_builtins_float16array

I wonder why it's used there, given it's only supported in Firefox so far. Perhaps the main branch of Webkit already has it.

Does the Web Inspector still work for you?

**Comment by HimbeersaftLP** [comment]
As for the error about saving settings: That could probably be fixed by implementing it in the InspectorFrontendHostStub.js file, which is responsible for "emulating" some native APIs.
I haven't checked if that is being called there, but I do return false for canSave, so there's that.
https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/blob/afb1a64bb57bcf9cf3068dafc21d820e12d68942/src/injectedCode/InspectorFrontendHostStub.js#L145

**Comment by MaZZly** [comment]
> Those files have always been missing. Given their name I assume they are proprietary additions specific to Safari.

Ahh okay, so that is not the problem then..

> Float16Array is an upcoming data type: https://caniuse.com/mdn-javascript_builtins_float16array
> I wonder why it's used there, given it's only supported in Firefox so far. Perhaps the main branch of Webkit already has it.

Yeah I was thinking the same, why would something like that be used... That's also why I was supsecting that maybe `WebInspectorUIAdditions.js` would implement some version of it..

> Does the Web Inspector still work for you?

Not really, cause anytime the cursor is moved, it triggers a new `Float16Array` error.

> As for the error about saving settings

If it also triggers for you and is not causing problems, I guess it is also irrelevant for my case...

- - - 

So I guess we would need to figure out where/what/why the `Float16Array` is being used there..

**Comment by HimbeersaftLP** [comment]
Hi @MaZZly it looks like Float16Array is used nowhere except in one utility function, so I just added a dummy and it works again: https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/commit/aeeb902f48f2b732322e72e0b51e63ea9589f122
You'll need to rerun the generate script

**Comment by HimbeersaftLP** [comment]
I'm assuming it works now. Feel free to reopen
