### ISSUE TITLE
Could not start com.apple.webinspector!: No error

### ISSUE THREAD

**Issue by superlucker** [HimbeersaftLP/ios-safari-remote-debug-kit#4]
Listing devices on :9221
Could not start com.apple.webinspector!: No error
Unable to attach 00008101-001A30422699001E inspector
IOS version 15.5
anyideas?

**Comment by HimbeersaftLP** [comment]
Hi, this appears to be a bug in Google's ios-webkit-debug-proxy. Sadly there is nothing I can do about that and it seems they don't really maintain it anymore either :/

https://github.com/google/ios-webkit-debug-proxy/issues/385

**Comment by arnoclr** [comment]
Same issue for me and I'm in Windows 11 (if it can help)

**Comment by FanningHau** [comment]
Same issue here on Win10

**Comment by FanningHau** [comment]
Same issue here on Win10

**Comment by MrStLouis** [comment]
replacing ios-webkit-debug-proxy with v1.9.0+ from here worked for me https://github.com/google/ios-webkit-debug-proxy

**Comment by HimbeersaftLP** [comment]
I updated the script to automatically download the new version now
