### ISSUE TITLE
Incorrect `InspectorBackendCommands.js` location

### ISSUE THREAD

**Issue by Sxxov** [HimbeersaftLP/ios-safari-remote-debug-kit#5]
The location for `InspectorBackendCommands.js` files have changed upstream, causing the `generate` scripts to fail. https://github.com/WebKit/WebKit/commit/98bfc3e264ced345a367f725b37f24c25ca08b88

**Comment by mockey** [comment]
It seems this change is not on SVN yet:
https://svn.webkit.org/repository/webkit/trunk/Source/WebInspectorUI/UserInterface/Protocol/Legacy/
So generate.sh fails atm.

**Comment by AndrewKvalheim** [comment]
Perhaps related to [this](https://webkit.org/blog/13140/webkit-on-github/):

> On June 23rd, the WebKit project froze its Subversion tree and transitioned management and interaction with our source code to `git` on [GitHub](https://github.com/WebKit/WebKit).

**Comment by HimbeersaftLP** [comment]
Thank you! I will change the bash script to also use git (or someone can PR if they feel like cuz I currently don't)

**Comment by AndrewKvalheim** [comment]
[Supposedly](https://stackoverflow.com/a/18194523) GitHub offers Subversion compatibility which could be useful to avoid downloading the entire WebKit repository, but it’s currently failing for me with “internal server error”. Maybe WebKit/WebKit is too large or new.

**Comment by HimbeersaftLP** [comment]
yeah, the powershell variant already does that: https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/blob/bfa15e76ec1c52caccf97ad1e0b5beaf1a1bea1a/src/generate.ps1#L11-L15

It's only a matter of copying and testing it

**Comment by HimbeersaftLP** [comment]
Sooo, is someone of you going to make a pull request?
(currently it's a great time to do so as Hacktoberfest is going on)
Otherwise I'll fix it once I get to it.

**Comment by AndrewKvalheim** [comment]
Don’t wait for me; I’m personally [using](https://gitlab.com/Andrew/configuration/-/blob/8200f625a4190f03cc7c631e56155607e8f89c21/packages/ios-safari-remote-debug-kit.nix) Nix instead of the script.

**Comment by HimbeersaftLP** [comment]
Fixed in https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/commit/e83e338a9baff7a0b74eeada2e8db41f9c7647c1

**Comment by HimbeersaftLP** [comment]
@AndrewKvalheim Nice to see a Nix user in the wild btw.
I also made some changes inspired by your nix file that I hope you like: https://github.com/HimbeersaftLP/ios-safari-remote-debug-kit/pull/11

btw, why are you removing the InspectorBackendCommands.js part, considering the page doesn't open without that file?
